version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - front_net
  ui:
    # build: ./ui
    image: xxxandr84/ui:1.0
    ports:
      - 9292:9292
    networks:
      - front_net
  post:
    # build: ./post-py
    image: xxxandr84/post:1.0
    networks:
      - front_net
  comment:
    # build: ./comment
    image: xxxandr84/comment:1.0
    networks:
      - front_net

volumes:
  post_db:

networks:
  front_net:
