

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'


    - name: bundle install
      bundler:
        state: present


  handlers:
  - name: restart puma
    become: true

