version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    # build: ./ui
    image: xxxandr84/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    # build: ./post-py
    image: xxxandr84/post:1.0
    networks:
      - front_net
      - back_net

  comment:
    # build: ./comment
    image: xxxandr84/comment:1.0
    networks:
      - front_net
      - back_net

  prometheus:
    image: xxxandr84/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net: